const en = {
	"cancel": "Cancel",
	"submit": "OK",
	"loading": "Loading",
	"request_fail": "Request Failed",
	"upload_fail": "Upload Failed",
	"request_tip": "Request Tip",
	"tips": "Tips",
	"store_close": "The store is closed ~ Please choose another one.",
	"ok": "OK",
	"order_now": "Order Now",
	"delivery": "Delivery",
	"home": "Home",
	"vip_card": "VIP Card",
	"my_stuff": "Member Center",
	"store": "Store",
	"switch": "Switch",
	"address_change": "Change",
	"find": "Find",
	"try_again": "Item not found, please try another ~",
	"selected": "Selected",
	"clear": "Clear",
	"total": "Total",
	"ready": "Checkout",
	"store_is_not_available": "The store is not available, please choose another one.",
	"stores": "Store List",
	"find_store": "Find a store",
	"store_is_not_exist": "The store is not found",
	"order_now_btn": "Order Now",
	"find_product": "Find a product",
	"product_name": "Product Name",
	"choose_city": "Select City",
	"current_city": "Current City",
	"hot_cities": "Popular Cities",
	"find_city": "Find a city",
	"product_details": "Product Details",
	"a_copy": "A copy",
	"add_shopping_cart": "Add to Shopping Cart",
	"shopping_cart": "Shopping Cart",
	"clear_cart": "Clear Shopping Cart",
	"current_store":  "Current Store",
	"totally":  "Total ",
	"products":  " Item",
	"done": "Done",
	"order_confirm": "Order Confirm",
	"bargain_purchase": "Bargain to add",
	"more_food": "More Food Options",
	"all": "All",
	"please": "Order Service Type",
	"choose_one": "Choose One",
	"eat_in": "Dine In",
	"take_away": "Take Away",
	"need_delivery_here": "Need Table Service?",
	"yes": "Yes",
	"no": "No",
	"table_no": "Table NO.",
	"use_coupons": "Use Coupons",
	"change": "Switch",
	"no_coupon": "Not use coupon",
	"no_available_coupon": "No available coupon",
	"no_available_point": "No available point",
	"points_deduction": "Points Deduction",
	"point_can_deduction": " Points = ￥",
	"use": "Use",
	"no_use": "No use",
	"available_points": "Available Points",
	"payment_channel": "Payment Method",
	"wechat_pay": "WeChat Pay",
	"need_tableware": "Need Tableware",
	"order_total": "Total ",
	"order_products": " Items",
	"pay": "Pay",
	"additional_purchase": "Value Additions",
	"add": "Add",
	"employee_discount": "Employee Discount",
	"price": "¥",
	"adress": "Address",
	"delivery_change": "Change",
	"choose_address": "Please choose an address.",
	"default": "Default",
	"add_address": "Add an address",
	"no_address": "No delivery address, please add one.",
	"add_shipping_address": "Add a delivery address",
	"contact": "Contact",
	"input_contact": "Please input a contact.",
	"gender": "Gender",
	"choose_male_female": "Please select gender",
	"cell_phone_number": "cell-phone number",
	"input_cell_phone": "Please input a cell-phone number",
	"shipping_address": "Shipping Address",
	"please_choose": "Please select",
	"input_more_address": "Please input an address, eg: Room *, NO. *, ** Road",
	"set_default_address": "Set as the default address",
	"save": "Save",
	"choose_an_address": "Select an address",
	"search_an_address": "Search an address",
	"welcome_vip": "Welcome be a POPEYES member",
	"improve_your_info": "Complete your info.",
	"member_center": "Member Center",
	"qr_expired_refresh": "The QR code has expired, please refresh.",
	"getting_qr_code.": "Getting a QR code.",
	"vip_card": "VIP Card",
	"my_points": "My Points",
	"order_history": "Order History",
	"my_coupons": "My Coupons",
	"coupons_details": "Coupon Details",
	"current_points": "Current Points",
	"point_detail": "Points History",
	"store_orders": "Store Orders",
	"delivery_orders": "Delivery Orders",
	"in_the_catering": "Preparing",
	"chargeback": "Ordered Canceled",
	"completed": "Completed",
	"canceled": "Canceled",
	"shipping": "On the way",
	"line_code": "Order Pickup Number",
	"no_orders_here": "No orders yet.",
	"your_order_prepared": "Your order is being prepared, thanks for your patience.",
	"paid": "Paid",
	"preparing": "Preparing",
	"taking": "Ready",
	"bargain_additions": "Bargain Additions",
	"bargain_addition": "Bargain Addition",
	"delivery_fee": "Delivery fee",
	"discount": "Discount",
	"payment_info": "Payment Info",
	"order_no": "Order NO.",
	"transaction_no": "Transaction NO.",
	"purchase_time": "Purchase Time",
	"dine_way": "Dining Method",
	"take_out": "Take-out",
	"dine_in": "Dine-In",
	"delivery_order": "Delivery Order",
	"catering": "Preparing",
	"shipping": "Delivering",
	"arrived": "Arrived",
	"delivery_man": "Rider",
	"distance": "Distance",
	"contact_rider": "Contact Rider",
	"receiver": "Receiver",
	"contact_now_rider": "Contact rider?",
	"contact_now": "Contact Now",
	"available": "Available",
	"expired": "Expired",
	"off": "Off",
	"use_now": "Use Now",
	"unlimited_coupons": "Standard Coupons",
	"use_over": "Valid when order over ￥ ",
	"terms_use": "Terms of use",
	"not_coupon": "You currentl don't have any coupon ~",
	"activity_details": "Promotion Details",
	"claim_now": "Claim Now",
	"activity_rules": "Activity Rules",
	"to": "To",
	"finished": "Finished",
	"received": "Received",
	"not_used": "Unused",
	"already_received": "Sorry, all available coupons have been claimed.",
	"done_with_it": "Sorry, all available coupons have been claimed.",
	"successful_reception": "Claimed",
	"address_over": "You can only have upto 10 delivery addresses",
	"confirm_delete": "Confirm Deletion",
	"delete_successful": "Deleted ucessfully",
	"edit_shipping_address": "Edit Address",
	"address_cannot_exceed_20": "Detailed address can not exceed 20 words",
	"address_updated_successfully": "Address Updated",
	"address_save_successfully": "Address Saved",
	"address_no_store": "There's no matching store serving this delivery address, would you choose a new address?",
	"city_no_store": "Currently there's no store  serving this city, please choose a different city",
	"up": " Up",
	"customization": "Customize",
	"no_more": "There is no more ",
	"portion": " Options",
	"input": "Input",
	"available_coupons": "Applicable Coupons",
	"nearest_to_you": "Stores closest to your location",
	"store_is_far_away": "The store is quite far from the delivery address, would you like to continue ordering?",
	"store_is_close": "The store is currently closed, please choose a different store",
	"need_more_points": "You need at least ",
	"need_more_points1": " points to use",
	"use_point_int": "Usage of points needs to be rounded to 10s",
	"input_table_no": "Please enter your table number",
	"pay_failed": "Payment unsucessful, please try again!",
	"waiting_orders": "Order waiting to be processed",
	"your_order_waiting": "Your order is waiting to be processed",
	"your_order_finished": "Your order has been completed",
	"outward_delivery": "Delivery",
	"o_use": "Use ",
	"o_use_point": " points",
	"call_phone": "Contact Mobile Number",
	"rest": "The store is currently closed",
	"no_seearch_product": "The product is not found, please try another one",
	"welcome_min": "Welcome to Popeyes China mini program!",
	"auth_local_tip": "In order to servce you better, we need your permission to obtain your location information.",
	"auth_local": "Authorize location service",
	"over_user_point": "Exceed the maximum applicable points per order",
	"comfirm_clear_shopping_cart": "Are you sure to empty shopping cart?",
	"get_coupon": "Effective within ",
	"validity_days": " days of picking-up",
	"contentdown_tip": 'Pull up to show more',
	"contentrefresh_tip": 'Loading …',
	"contentnomore_tip": 'No more data',
	"privacy_title": "Popeyes Membership Agreement and Privacy Policies",
	"member_register": "Member Registration",
	"member_register_tip": "Become a Popeyes member, enjoy many exciting benefits",
	"member_register_btn": "Fast registration by WeChat",
	"remarks": "Notes",
	"input_remarks": "Please type notes",
	"product_coupon": "Coupons",
	"go_sok_sign": "Check-in at self-ordering Kiosks",
	"go_sok_sign_tip": "Please proceed to self-ordering Kiosks to check-in",
	"go_sok_sign_title": "My check-in number",
	"dine_way_time": "Time of Dining",
	"dine_way_now": "Dine Imediately",
	"dine_way_apt": "Appointment Time",
	"dine_way_select_time": "Your appointment time",
	"continue_to_choose": "Continue Shopping",
	"my_product_title": "My product coupons",
	"please_choose_apt_time": "Please select appointment time",
	"im_agree_read": "I have read and agree to the ",
	"popeyes_privacy_info": "Popeyes membership agreement and Privacy Policies",
	"avalibable_times": "Availble time period",
	"successful_add_cart": "Availble time period",
	"immediate_use": "Use Immediately",
	"coupon_tip": "Coupons",
	"member_price": "Member Price",
	"deducted": "Already Deducted",
	"tack_out_no_open": "Delivery service coming soon. Thank you!",
	"order_coupon": "Order Coupon",
	"my_product_coupon": "Product Coupon",
	"no_thanks": "No，thank you!",
	"product_txt": "Product",
	"add_cart_over": "Exceeded Maximum Order Quantity",
	"d_items": "items",
	"rest": "Closed"
}

export default en;