const otherEn = {
    "sok_select_language": "Please select language",
    "sok_login_qr_code": "Member login by QR code",
    "sok_login_scan_code": "Scan Code",
    "sok_login_scan_code_tip": "Please scan the QR code of APP member or order",
    "sok_phone_login": "Mobile login",
    "sok_input_mobile_number": "Please input mobile number",
    "sok_send_code": "Send Verification Code",
    "sok_sending": "Sending...",
    "sok_input_code": "Please input the verification code",
    "sok_confirm": "Confirm",
    "sok_show_code": "Mini Program Code",
    "sok_show_code1": "Scan “My Member Code”",
    "sok_show_code2": "or order QR code",
    "sok_identifying": "Identifying",
    "sok_identifying_success": "Code scanning success",
    "sok_identifying_success_tip": "Welcome to PoPeyes",
    "sok_identifying_order_success": " please check your order number",
    "sok_identifying_order_success2": "on POPEYES WeChat Mini Program",
    "sok_identifying_failed": "Identification failed.",
    "sok_refresh_code": "Please refreash the QR code and re-idendify.",
    "sok_alipay": "Alipay",
    "sok_alipay_face": "AliPay with Face Recognition",
    "sok_pay_code": "Please show your payment code",
    "sok_confirm_pay": "Confirm to pay",
    "sok_paying": "Paying",
    "sok_pay_success": "Paid Successfully",
    "sok_pay_failed": "Paid Failed.",
    "sok_pay_refresh": "Please try again.",
    "sok_take_receipt": "Please take your receipt in time",
    "sok_pickup_number": "Order Pickup Number",
    "sok_back": "Back",
    "sok_dine_in": "Dine-In",
    "sok_take_out": "Take-out",
    "sok_actually_paid": "Actually paid",
    "sok_items_added": " Items added",
    "sok_welcome_to": "Welcome to POPEYES",
    "sok_store_phone": "cell-phone number",
    "sok_pickup_number1": "Pickup Number",
    "sok_select_payment": "Select a payment method",
    "sok_done": "Done",
    "sok_no_tip1": "Can't get the pick-up number,",
    "sok_no_tip2": "please contact the clerk.",
    "sok_edit": "Edit",
    "sok_ready": "Done",
    "sok_scan_coupon_tip1": "或使用手动输入",
    "never_notify": "不再提醒",
    "sok_scan_coupon_input": "手工输入",
    "sok_scan_coupon": "Scan Coupon",
    "sok_scan_coupon_success": "Successful!",
    "sok_scan_coupon_fail": "Failed",
    "sok_scan_pay": "AliPay/WeChat Pay",
    "one_coupon": "one coupon per order",
    "sok_sign_overtime": "Code already expired, please get again on mini program",
    "sok_order_limit1": "Due to high demand, limit",
    "sok_order_limit2": "one order per person and 500 RMB",
    "sok_order_limit3": "per order on pre-discount price",
    "sok_order_limit_btn": "I acknowledge",
    "logout": "Logout",
    "sok_coupon_txt": "Coupon",
    "that_ok": "That's OK"
}

export default otherEn;